"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import numpy
import math
import functools
from pprint import pprint


def primesfrom2to(n):
    # http://stackoverflow.com/questions/2068372/fastest-way-to-list-all-primes-below-n-in-python/3035188#3035188
    sieve = numpy.ones(n//3 + (n%6==2), dtype=numpy.bool)
    sieve[0] = False
    for i in range(int(n**0.5)//3+1):
        if sieve[i]:
            k=int(3*i+1|1)
            sieve[   int((k*k)/3)      ::2*k] = False
            sieve[int((k*k+4*k-2*k*(i&1))/3)::2*k] = False
    return numpy.r_[2,3,((3*numpy.nonzero(sieve)[0]+1)|1)]


def find_triangle_numbers(n):
    return sum(range(1, n+1))


def find_factors(n):
    step = 2 if n%2 else 1
    temp = ([i, n // i] for i in range(1, int(math.sqrt(n)) + 1, step) if n % i == 0)

    return set(functools.reduce(list.__add__,
                                temp))

def oldway():
    i = 2
    factors = []
    while len(factors) < 10:
        triangle = find_triangle_numbers(i)
        prime_of_triangle = primesfrom2to(triangle)
        factors = [ i for i in prime_of_triangle if triangle % i == 0]
        factors.append(1)
        factors.append(triangle)
        for num in set(factors):
            temp = triangle / num
            if temp != 0:
                factors.append(int(temp))
        sqr = math.sqrt(triangle)
        if sqr == math.ceil(sqr):
            factors.append(int(sqr))
        i += 1
        factors = set(factors)
    print(triangle, len(factors), factors)


def testing(n):
    step = 2 if n/2 else 1
    temp = ([i, n // i] for i in range(1, int(math.sqrt(n)) + 1, step) if n % i == 0)
    for i in temp:
        print(i)
    return temp

def main():
    start = 1
    currentNum = 0
    len_of_factor = 0
    while len_of_factor <= 50:
        currentNum += start
        start += 1
        factors = find_factors(currentNum)
        len_of_factor = len(factors)
    # print(currentNum, len_of_factor, factors)
    return(currentNum)


if __name__ == "__main__": main()

