"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def main():
    i = 0
    y = 1
    temp = 0
    holdme = []
    while(True):
        temp = i + y
        if(temp > 4 * 10**6):
            break
        i = y
        y = temp
        holdme.append(y)
    return(sum([i for i in holdme if i%2 == 0]))

if __name__ == "__main__": main()
